name: CI Pipeline

on:
  push:
    branches:
      - main  # Adjust to your main development branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Pull the custom Docker image
      - name: Pull Docker image
        run: docker pull stekajack/ubuntults_with_espresso_magnetodynamics_wip

      # Step 3: Run tests in the Docker container
      - name: Run tests in custom Docker container
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          stekajack/ubuntults_with_espresso_magnetodynamics_wip \
          bash -c "
            pip3 install -e . &&
            python3 -m unittest discover -s test
          "