name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Pull the custom Docker image
      - name: Pull Docker image
        run: docker pull stekajack/ubuntults_with_espresso_magnetodynamics_wip

      # Step 3: Build and deploy documentation
      - name: Build and deploy documentation
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          stekajack/ubuntults_with_espresso_magnetodynamics_wip \
          bash -c "
            # Install the pressomancy package and Sphinx dependencies
            pip3 install -e . &&
            pip3 install sphinx sphinx_rtd_theme &&
            
            # Navigate to the Sphinx docs directory and build documentation
            cd doc/sphinx &&
            python3 -m sphinx.cmd.build -b html source build &&
            
            # Copy the built HTML files back to the workspace
            cp -r build /workspace/doc/sphinx/build
          "

      # Step 4: Deploy documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git switch gh-pages
          rm -rf *  # Clear old content
          cp -r doc/sphinx/build/* .  # Copy new documentation
          touch .nojekyll  # Disable Jekyll processing
          git add .
          git commit -m "Deploy updated documentation [skip ci]"
          git push -f origin gh-pages