name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Pull the custom Docker image
      - name: Pull Docker image
        run: docker pull stekajack/ubuntults_with_espresso_magnetodynamics_wip

      # Step 3: Build documentation
      - name: Build documentation
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          stekajack/ubuntults_with_espresso_magnetodynamics_wip \
          bash -c "
            pip3 install -e . &&
            pip3 install sphinx sphinx_rtd_theme &&
            cd doc/sphinx &&
            python3 -m sphinx.cmd.build -b html source build
          "

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git switch gh-pages
          rm -rf *  # Remove all files in the gh-pages branch
          cp -r doc/sphinx/build/* .  # Copy the new documentation to the root of the gh-pages branch
          touch .nojekyll  # Disable Jekyll processing on GitHub Pages
          git add .
          git commit -m "Deploy updated documentation [skip ci]"
          git push -f origin gh-pages