name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Pull the custom Docker image
      - name: Pull Docker image
        run: docker pull stekajack/ubuntults_with_espresso_magnetodynamics_wip

      # Step 3: Build documentation
      - name: Build documentation
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          stekajack/ubuntults_with_espresso_magnetodynamics_wip \
          bash -c "
            pip3 install -e . &&
            pip3 install sphinx sphinx_rtd_theme &&
            cd doc/sphinx &&
            python3 -m sphinx.cmd.build -b html source build
          "

      # Step 4: Upload documentation artifact
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc/sphinx/build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}